apiVersion: v1
kind: Service
metadata:
  labels:
    name.service: {{ .Values.mongodbService }}
  name: {{ .Values.mongodbService }}
spec:
  ports:
    - name: "27017"
      port: {{ .Values.mongodbPort }}
      targetPort: {{ .Values.mongodbPort }}
  selector:
    name.service: {{ .Values.mongodbService }}
status:
  loadBalancer: {}
