apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name.service: {{ .Values.mongodbService }}
  name: {{ .Values.mongodbService }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name.service: {{ .Values.mongodbService }}
  strategy: {}
  template:
    metadata:
      labels:
        name.service: {{ .Values.mongodbService }}
    spec:
      containers:
        - env:
            - name: MONGODB_PASSWORD
              value: '{{ .Values.mongodbPass }}'
            - name: MONGODB_USER
              value: '{{ .Values.mongodbUser }}'  
            - name: MONGODB_ADMIN_PASSWORD
              value: '{{ .Values.mongodbAdminPass }}'
            - name: MONGODB_DATABASE
              value: '{{ .Values.mongodbDatabase }}'  
          name: {{ .Values.mongodbService }}
          image: {{ .Values.mongodbImage }}
          ports:
            - containerPort: {{ .Values.mongodbPort }}
          resources: {}
      restartPolicy: Always
status: {}
